language: python
python:
  - "3.6"
install:
 - pip install tox
 - pip install -r requirements.txt
script:
 - tox
env:
 - TOXENV=py27-django18
 - TOXENV=py27-django111
 - TOXENV=py37-django18
 - TOXENV=py37-django111
 - TOXENV=py37-django22
