language: python
python:
  - "2.7"
  - "3.7"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.2

matrix:
  exclude:
    - python: '2.7'
      env: 'DJANGO_VERSION=2.2'

install:
 - pip install -U Django==$DJANGO_VERSION
 - pip install -r requirements.txt

script:
 - DJANGO_SETTINGS_MODULE=testproject.settings django-admin.py test
